apps/inventory/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import AddItemForm, UpdateItemForm
from .models import Inventory
from .views import (
    AddInventoryView, QuickQuantityUpdateView, ReportView, SaveQuantityValue, UpdateInventoryListView,
    UpdateInventoryView
)

app_name = 'inventory'
urlpatterns = [
    url(
        r'^add/$',
        AddInventoryView.as_view(
            action='Add',
            form_class=AddItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been added',
            success_url=reverse_lazy('inventory:add'),
            template_name='inventory/form.html'
        ),
        name='add'
    ),

    url(
        r'^quick/$',
        QuickQuantityUpdateView.as_view(
            model=Inventory,
            template_name='inventory/quick_quantity_update_list.html'
        ),
        name='quick_quantity_update'
    ),

    url(
        r'^report/$',
        ReportView.as_view(
            model=Inventory,
            template_name='reports/inventory.html'
        ),
        name='report'
    ),

    url(
        r'^save/quantity/$',
        SaveQuantityValue.as_view(),
        name='save_quantity_values'
    ),

    url(
        r'^update/$',
        UpdateInventoryListView.as_view(
            model=Inventory,
            template_name='inventory/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateInventoryView.as_view(
            action='Update',
            form_class=UpdateItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been updated',
            success_url=reverse_lazy('inventory:list'),
            template_name='inventory/form.html'
        ),
        name='update'
    )
]

shopowner/urls.py
from dashing.utils import router

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from dashboard.widgets import QuickSummaryWidget
from dashboard.wrapper import Wrapper

from library.forms import popup

router.register(QuickSummaryWidget, 'quick_summary_widget')


urlpatterns = [
    url(r'^$', Wrapper.as_view()),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^add_popup/(?P<app_label>\w*)/(?P<model_name>\w*)/', popup.popup_form),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(router.urls), name='dashboard'),
    url(r'^data_transfer/', include('data_transfer.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^orders/', include('orders.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files(?P<path>.*)$', serve, kwargs={'document_root': settings.MEDIA_ROOT})
    ]

apps/inventory/models.py
from django.contrib.auth.models import User
from django.db import models

from vendors.models import Vendor


class Inventory(models.Model):
    deleted = models.BooleanField(default=False, help_text='Delete this item from inventory')

    label = models.CharField(
        help_text="Item label for display",
        max_length=100
    )

    notes = models.TextField(
        blank=True,
        help_text='Any miscellaneous information can go here'
    )

    qty_bought = models.PositiveIntegerField(
        default=0,
        help_text='Quantity of this item purchased'
    )

    qty_sold = models.PositiveIntegerField(
        default=0,
        help_text='Quantity of this item sold'
    )

    product_number = models.CharField(
        help_text="Vendor's product number for this item",
        max_length=50,
    )

    stock_number = models.CharField(
        help_text="My stock number for this item",
        max_length=50,
    )

    wholesale_price = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Wholesale price per item unit',
        max_digits=10,
    )

    user = models.ForeignKey(
        User,
        help_text="User account this item belongs to"
    )

    vendor = models.ForeignKey(
        Vendor,
        blank=True,
        help_text='Vendor this item was purchased from',
        null=True
    )

    class Meta:
        ordering = ('label',)
        unique_together = ('label', 'product_number', 'stock_number', 'user', 'vendor')
        verbose_name_plural = 'Inventories'

    def price_per_unit(self, total_cost):
        return total_cost / self.qty_bought

    @property
    def remaining(self):
        return self.qty_bought - self.qty_sold

    def __str__(self):
        return self.label

apps/inventory/forms.py
from django import forms

from library.forms import SelectWithAdd

from .models import Inventory


class BaseItemForm(forms.ModelForm):
    class Meta:
        fields = ['label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'notes']
        model = Inventory
        widgets = {
            'vendor': SelectWithAdd(Inventory.vendor)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['notes'].required = False
        self.fields['product_number'].required = False
        self.fields['stock_number'].required = False


class AddItemForm(BaseItemForm):
    pass


class AddItemPopupForm(BaseItemForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['qty_bought'].required = False
        self.fields['wholesale_price'].required = False

    class Meta(BaseItemForm.Meta):
        fields = ['label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'notes', 'user']
        widgets = {
            'user': forms.HiddenInput
        }


class UpdateItemForm(BaseItemForm):
    class Meta(BaseItemForm.Meta):
        fields = [
            'label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'qty_sold', 'notes',
            'deleted'
        ]

apps/inventory/views.py
from django.http import HttpResponse

from .models import Inventory

from library.views.generic import AppCreateView, AppListView, AppTemplateView, AppUpdateView
from library.views.generic.mixins.ajax import AJAXResponseMixin


class AddInventoryView(AppCreateView):
    pass


class QuickQuantityUpdateView(AppListView):
    pass


class SaveQuantityValue(AJAXResponseMixin, AppTemplateView):
    def post(self, request, *args, **kwargs):
        item = Inventory.objects.get(id=self.request.POST['item_id'])
        setattr(item, self.request.POST['field'], self.request.POST['new_value'])
        item.save()

        return super().post(request, *args, **kwargs)


class ReportView(AppListView):
    pass


class UpdateInventoryListView(AppListView):
    pass


class UpdateInventoryView(AppUpdateView):
    pass

templates/inventory/_inventory_list.html
{% extends "reports/_list_base.html" %}


{% block data_table_headers %}
    <th>Label</th>
    <th>Vendor</th>
    <th>Wholesale Price/Unit</th>
    <th>Quantity Bought</th>
    <th>Quantity Sold</th>
    <th>Quantity Remaining</th>
{% endblock %}

{% block data_table_data %}
    {% for item in object_list %}
        <tr data-id="{{ item.id }}" data-my_stock_number="{{ item.stock_number }}"
            data-vendor_product_number="{{ item.product_number }}" data-notes="{{ item.notes }}">
            <td>{{ item.label }}</td>
            <td>{{ item.vendor }}</td>
            <td class="text-end">${{ item.wholesale_price }}</td>
            <td class="text-end">{{ item.qty_bought }}</td>
            <td class="text-end">{{ item.qty_sold }}</td>
            <td class="text-end">{{ item.remaining }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block data_table_no_item_label %}items in inventory{% endblock %}

templates/inventory/_list.html
{% extends "reports/_list_base.html" %}


{% block data_table_headers %}
    <th>Label</th>
    <th>Vendor</th>
    <th>Wholesale Price/Unit</th>
    <th>Quantity Bought</th>
    <th>Quantity Sold</th>
    <th>Quantity Remaining</th>
{% endblock %}

{% block data_table_data %}
    {% for item in object_list %}
        <tr data-id="{{ item.id }}" data-my_stock_number="{{ item.stock_number }}"
            data-vendor_product_number="{{ item.product_number }}" data-notes="{{ item.notes }}">
            <td>{{ item.label }}</td>
            <td>{{ item.vendor }}</td>
            <td class="text-end">${{ item.wholesale_price }}</td>
            <td class="text-end">{{ item.qty_bought }}</td>
            <td class="text-end">{{ item.qty_sold }}</td>
            <td class="text-end">{{ item.remaining }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block data_table_no_item_label %}items in inventory{% endblock %}

templates/inventory/form.html
{% extends "base.html" %}
{% load static %}

{% block js %}
    {{ block.super }}

    <script src="{% static "admin/js/jquery.init.js" %}" type="text/javascript"></script>
    <script src="{% static "admin/js/admin/RelatedObjectLookups.js" %}" type="text/javascript"></script>
{% endblock %}


{% block content %}
    <div class="pb-2 mt-4 mb-2 border-bottom"><h1>{{ action }} Inventory</h1></div>

    {% include "_bootstrap_form.html" %}
{% endblock %}

templates/inventory/quick_quantity_update_list.html
{% extends "inventory/_list.html" %}
{% load static %}

{% block css %}
    {{ block.super }}

    <style>
        #data_table {
            cursor: default;
        }

        #data_table tr td:nth-of-type(4), #data_table tr td:nth-of-type(5) {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block ready_js %}
    let csrftoken = Cookies.get('csrftoken');

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function csrfSafeMethod(method) {
        // These HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    dataTable.MakeCellsEditable({
        "allowNulls": {
            "columns": []
        },
        "columns": [3, 4],
        "confirmationButton": {
            "confirmCss": "btn btn-success btn-sm",
            "cancelCss": "btn btn-danger btn-sm",
            "listenToKeys": true
        },
        "inputTypes": [
            {
                "column": 3,
                "type": "number"
            },
            {
                "column": 4,
                "type": "number"
            }
        ],
        "onUpdate": storeUpdatedValue,
        "onValidate": validateUpdatedValue
    });
{% endblock %}

{% block js %}
    {{ block.super }}

    <script type="text/javascript" src="{% static 'js/js.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static "js/dataTables.cellEdit.js" %}"></script>

    <script>
        function storeUpdatedValue(updatedCell, updatedRow, oldValue) {
            if (updatedCell.data() !== oldValue) {
                let field = (updatedCell.index()["column"] === 3) ? "qty_bought" : "qty_sold";
                let newValue = updatedCell.data();

                $.post(
                    "{% url "inventory:save_quantity_values" %}",
                    {
                        "field": field,
                        "item_id": updatedRow.nodes().to$().data("id"),
                        "new_value": newValue
                    },
                    function() {
                        // Update the Quantity Remaining column after the bought or sold value has been changed
                        let data = updatedRow.data();
                        data[5] = data[3] - data[4];
                        updatedRow.data(data).draw();
                    }
                ).fail(function(jqXHR, textStatus, errorThrown) {
                    alert(
                        "Could not save quantity information.\n\nError: " + jqXHR.responseText
                    );
                });
            }
        }

        function validateUpdatedValue(cell, row, newValue) {
            return !isNaN(newValue);
        }
    </script>
{% endblock %}

{% block header %}Quick Quantity Update{% endblock %}

templates/inventory/update_list.html
{% extends "inventory/_list.html" %}

{% block header %}Update Inventory{% endblock %}

{% block data_table_handler %}
    window.location.replace("{% url "inventory:update" 0 %}".replace('0', $(this).data("id")));
{% endblock %}

{% block instructions %}
    <p>Click on an item's row to edit the information.</p>
{% endblock %}