apps/inventory/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import AddItemForm, UpdateItemForm
from .models import Inventory
from .views import (
    AddInventoryView, QuickQuantityUpdateView, ReportView, SaveQuantityValue, UpdateInventoryListView,
    UpdateInventoryView
)

app_name = 'inventory'
urlpatterns = [
    url(
        r'^add/$',
        AddInventoryView.as_view(
            action='Add',
            form_class=AddItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been added',
            success_url=reverse_lazy('inventory:add'),
            template_name='inventory/form.html'
        ),
        name='add'
    ),

    url(
        r'^quick/$',
        QuickQuantityUpdateView.as_view(
            model=Inventory,
            template_name='inventory/quick_quantity_update_list.html'
        ),
        name='quick_quantity_update'
    ),

    url(
        r'^report/$',
        ReportView.as_view(
            model=Inventory,
            template_name='reports/inventory.html'
        ),
        name='report'
    ),

    url(
        r'^save/quantity/$',
        SaveQuantityValue.as_view(),
        name='save_quantity_values'
    ),

    url(
        r'^update/$',
        UpdateInventoryListView.as_view(
            model=Inventory,
            template_name='inventory/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateInventoryView.as_view(
            action='Update',
            form_class=UpdateItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been updated',
            success_url=reverse_lazy('inventory:list'),
            template_name='inventory/form.html'
        ),
        name='update'
    )
]

apps/orders/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import CreateOrderForm, UpdateOrderForm
from .models import Order
from .views import CreateOrderView, FetchInventory, ReportView, UpdateOrderListView, UpdateOrderView

app_name = 'orders'
urlpatterns = [
    url(
        r'^create/$',
        CreateOrderView.as_view(
            action='Create',
            form_class=CreateOrderForm,
            model=Order,
            success_message='Order has been created',
            success_url=reverse_lazy('orders:create'),
            template_name='orders/form.html'
        ),
        name='create'
    ),

    url(
        r'^fetch/inventory/$',
        FetchInventory.as_view(),
        name='fetch_inventory'
    ),
    url(
        r'^report/$',
        ReportView.as_view(
            model=Order,
            template_name='reports/orders.html'
        ),
        name='report'
    ),

    url(
        r'^update/$',
        UpdateOrderListView.as_view(
            model=Order,
            template_name='orders/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateOrderView.as_view(
            action='Update',
            form_class=UpdateOrderForm,
            model=Order,
            success_message='Order has been updated',
            success_url=reverse_lazy('orders:list'),
            template_name='orders/form.html'
        ),
        name='update'
    )
]

shopowner/urls.py
from dashing.utils import router

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from dashboard.widgets import QuickSummaryWidget
from dashboard.wrapper import Wrapper

from library.forms import popup

router.register(QuickSummaryWidget, 'quick_summary_widget')


urlpatterns = [
    url(r'^$', Wrapper.as_view()),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^add_popup/(?P<app_label>\w*)/(?P<model_name>\w*)/', popup.popup_form),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(router.urls), name='dashboard'),
    url(r'^data_transfer/', include('data_transfer.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^orders/', include('orders.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files(?P<path>.*)$', serve, kwargs={'document_root': settings.MEDIA_ROOT})
    ]

apps/inventory/models.py
from django.contrib.auth.models import User
from django.db import models

from vendors.models import Vendor


class Inventory(models.Model):
    deleted = models.BooleanField(default=False, help_text='Delete this item from inventory')

    label = models.CharField(
        help_text="Item label for display",
        max_length=100
    )

    notes = models.TextField(
        blank=True,
        help_text='Any miscellaneous information can go here'
    )

    qty_bought = models.PositiveIntegerField(
        default=0,
        help_text='Quantity of this item purchased'
    )

    qty_sold = models.PositiveIntegerField(
        default=0,
        help_text='Quantity of this item sold'
    )

    product_number = models.CharField(
        help_text="Vendor's product number for this item",
        max_length=50,
    )

    stock_number = models.CharField(
        help_text="My stock number for this item",
        max_length=50,
    )

    wholesale_price = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Wholesale price per item unit',
        max_digits=10,
    )

    user = models.ForeignKey(
        User,
        help_text="User account this item belongs to"
    )

    vendor = models.ForeignKey(
        Vendor,
        blank=True,
        help_text='Vendor this item was purchased from',
        null=True
    )

    class Meta:
        ordering = ('label',)
        unique_together = ('label', 'product_number', 'stock_number', 'user', 'vendor')
        verbose_name_plural = 'Inventories'

    def price_per_unit(self, total_cost):
        return total_cost / self.qty_bought

    @property
    def remaining(self):
        return self.qty_bought - self.qty_sold

    def __str__(self):
        return self.label

apps/orders/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

from artifacts.models import Artifact
from inventory.models import Inventory

from vendors.models import Vendor


class Item(models.Model):
    item = models.ForeignKey(Inventory)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])

    class Meta:
        ordering = ('order', 'item')
        unique_together = ('order', 'item')

    def __str__(self):
        return f'{self.item} <--> {self.order}'


class Order(models.Model):
    deleted = models.BooleanField(default=False, help_text='Delete this order from the database')

    user = models.ForeignKey(
        User,
        help_text="User account this order belongs to"
    )

    reference_number = models.CharField(
        blank=True,
        help_text='Order number/reference number',
        max_length=20,
        null=True
    )

    vendor = models.ForeignKey(
        Vendor,
        help_text='Vendor this order was purchased from'
    )

    items = models.ManyToManyField(
        Inventory,
        help_text='Items bought in this order',
        through=Item
    )

    date_ordered = models.DateField(
        blank=True,
        help_text='Date when order was placed',
        null=True
    )

    date_received = models.DateField(
        blank=True,
        help_text='Date when order was received',
        null=True
    )

    net_cost = models.DecimalField(
        decimal_places=2,
        help_text='Net cost for the order',
        max_digits=10,
    )

    shipping_cost = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Tax credit paid for the order',
        max_digits=10,
    )

    picked_up = models.NullBooleanField(
        default=None,
        help_text='True if the order was picked up, False if shipping cost, otherwise None for unknown status'
    )

    tax = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Tax credit paid for the order',
        max_digits=10,
    )

    payment_method = models.ForeignKey(
        'PaymentMethod',
        blank=True,
        help_text='Method of payment for this order',
        null=True
    )

    receipts = models.ManyToManyField(
        Artifact,
        blank=True,
        help_text='Uploaded receipt documents associated with this order'
    )

    notes = models.TextField(
        blank=True,
        help_text='Any miscellaneous information can go here'
    )

    class Meta:
        ordering = ('date_ordered', 'date_received', 'vendor', 'reference_number')

    @property
    def total_cost(self):
        return self.net_cost + self.shipping_cost

    def __str__(self):
        return f'[{self.vendor.name}] {self.reference_number}'


class PaymentMethod(models.Model):
    label = models.CharField(
        help_text='Method of payment',
        max_length=30,
        unique=True
    )

    class Meta:
        ordering = ('label', )

    def __str__(self):
        return self.label

apps/inventory/forms.py
from django import forms

from library.forms import SelectWithAdd

from .models import Inventory


class BaseItemForm(forms.ModelForm):
    class Meta:
        fields = ['label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'notes']
        model = Inventory
        widgets = {
            'vendor': SelectWithAdd(Inventory.vendor)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['notes'].required = False
        self.fields['product_number'].required = False
        self.fields['stock_number'].required = False


class AddItemForm(BaseItemForm):
    pass


class AddItemPopupForm(BaseItemForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['qty_bought'].required = False
        self.fields['wholesale_price'].required = False

    class Meta(BaseItemForm.Meta):
        fields = ['label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'notes', 'user']
        widgets = {
            'user': forms.HiddenInput
        }


class UpdateItemForm(BaseItemForm):
    class Meta(BaseItemForm.Meta):
        fields = [
            'label', 'stock_number', 'vendor', 'product_number', 'wholesale_price', 'qty_bought', 'qty_sold', 'notes',
            'deleted'
        ]

apps/orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from library.forms import FormsetField, HTML5DateInput, SelectWithAdd, SelectMultipleWithAdd

from .models import Item, Order

from inventory.models import Inventory


class ItemForm(forms.ModelForm):
    class Meta:
        exclude = ()
        model = Item
        widgets = {
            'item': SelectWithAdd(Item.item)
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['item'].queryset = Inventory.objects.filter(user=user)


ItemFormSet = forms.inlineformset_factory(Order, Item, exclude=['order'], extra=0, form=ItemForm)


class BaseOrderForm(forms.ModelForm):
    items = FormsetField(
        error_messages={
            'invalid': 'Quantity must be greater than 0',
            'required': 'Items bought in this order must be listed'
        },
        formset=ItemFormSet,
        help_text='Items bought in this order'
    )

    class Meta:
        fields = [
            'date_ordered', 'date_received', 'vendor', 'reference_number', 'items', 'net_cost', 'shipping_cost', 'tax',
            'payment_method', 'receipts', 'notes'
        ]
        model = Order
        widgets = {
            'date_ordered': HTML5DateInput(),
            'date_received': HTML5DateInput(),
            'payment_method': SelectWithAdd(Order.payment_method),
            'receipts': SelectMultipleWithAdd(
                Order.receipts, parameters={'category': 'receipt', 'directory': 'receipts'}
            ),
            'vendor': SelectWithAdd(Order.vendor)
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['items'].create_widget(ItemFormSet, form_kwargs={'instance': kwargs['instance'], 'user': user})


class CreateOrderForm(BaseOrderForm):
    update_quantity = forms.BooleanField(widget=forms.HiddenInput(), required=False)


class UpdateOrderForm(BaseOrderForm):
    class Meta(BaseOrderForm.Meta):
        fields = [
            'date_ordered', 'date_received', 'reference_number', 'vendor', 'items', 'net_cost', 'shipping_cost',
            'tax', 'payment_method', 'receipts', 'notes', 'deleted'
        ]

    def clean(self):
        cleaned_data = super().clean()

        if len(cleaned_data['items'].deleted_forms) == len(cleaned_data['items']):
            raise ValidationError('Items bought in this order must be listed', code='required')

        return cleaned_data

apps/inventory/views.py
from django.http import HttpResponse

from .models import Inventory

from library.views.generic import AppCreateView, AppListView, AppTemplateView, AppUpdateView
from library.views.generic.mixins.ajax import AJAXResponseMixin


class AddInventoryView(AppCreateView):
    pass


class QuickQuantityUpdateView(AppListView):
    pass


class SaveQuantityValue(AJAXResponseMixin, AppTemplateView):
    def post(self, request, *args, **kwargs):
        item = Inventory.objects.get(id=self.request.POST['item_id'])
        setattr(item, self.request.POST['field'], self.request.POST['new_value'])
        item.save()

        return super().post(request, *args, **kwargs)


class ReportView(AppListView):
    pass


class UpdateInventoryListView(AppListView):
    pass


class UpdateInventoryView(AppUpdateView):
    pass

apps/orders/views.py
from django.http import HttpResponseRedirect

from .models import Order

from library.views.generic import AppCreateView, AppListView, AppTemplateView, AppUpdateView
from library.views.generic.mixins.ajax import AJAXResponseMixin


class CreateOrderView(AppCreateView):
    object = None

    def form_valid(self, form):
        update_quantity = 'update_quantity' in form.cleaned_data and form.cleaned_data['update_quantity']

        self.object = form.save(commit=False)
        if self.object.shipping_cost:
            self.object.picked_up = False
        self.object.user = self.request.user
        self.object.save()

        for item in form.cleaned_data['items'].save(commit=False):
            item.order = self.object
            item.save()

            if update_quantity:
                item.item.qty_bought += item.quantity
                item.item.save()

        if self.success_message:
            self.success_message = self.success_message % form.cleaned_data

        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class FetchInventory(AJAXResponseMixin, AppTemplateView):
    def get_context_data(self, **kwargs):
        order = Order.objects.get(id=self.request.GET['order_id'])
        ret = []
        for item in order.item_set.all():
            ret.append([item.item.label, item.quantity])
        return ret


class ReportView(AppListView):
    pass


class UpdateOrderListView(AppListView):
    pass


class UpdateOrderView(AppUpdateView):
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.shipping_cost:
            self.object.picked_up = False
        self.object.user = self.request.user
        self.object.save()

        for item in form.cleaned_data['items'].deleted_forms:
            item.instance.delete()

        for item in form.cleaned_data['items'].save(commit=False):
            item.order = self.object
            item.save()

        if self.success_message:
            self.success_message = self.success_message % form.cleaned_data

        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

templates/reports/_list_base.html
{% extends "base.html" %}

{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">

    <style>
        #data_table {
            cursor: pointer;
        }

        th {
            text-align: center !important;
        }

        .top_align {
            vertical-align: top;
        }
    </style>
{% endblock %}

{% block js %}
    {{ block.super }}

    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>

    <!--suppress JSUnresolvedFunction -->
    <script>
        $(document).ready(function () {
            let dataTable = $("#data_table").DataTable({
                pageLength: 25
            });

            $("a").click(function(event) {
                event.stopPropagation();
            });

            $(".dataTable").on("click", "tbody tr", function() {
                {% block data_table_handler %}{% endblock %}
            });

            {% block ready_js %}{% endblock %}
        });
    </script>
{% endblock %}

{% block content %}
    <div class="pb-2 mt-4 mb-2 border-bottom"><h1>{% block header %}{% endblock %}</h1></div>

    {% if object_list %}
        {% block instructions %}{% endblock %}

        <table class="table table-striped table-bordered" id="data_table">
            <thead>
                <tr>{% block data_table_headers %}{% endblock %}</tr>
            </thead>

            <tbody>{% block data_table_data %}{% endblock %}</tbody>
        </table>
    {% else %}
        <p>No {% block data_table_no_item_label %}orders{% endblock %} to list</p>
    {% endif %}

    {% block extra_content %}{% endblock %}
{% endblock %}

templates/reports/inventory.html
{% extends "inventory/_list.html" %}

{% block header %}Inventory Report{% endblock %}

{% block data_table_handler %}
    let extraInfoModal = new bootstrap.Modal(document.getElementById("extraInfo"));

    $("#item_label").html(dataTable.row(this).data()[0]);
    $("#notes").html($(this).data("notes"));
    $("#my_stock_number").html($(this).data("my_stock_number"));
    $("#vendor_product_number").html($(this).data("vendor_product_number"));

    extraInfoModal.show();
{% endblock %}

{% block instructions %}
    <p>Click on an item's row to pop up more information.</p>
{% endblock %}

{% block extra_content %}
    <div class="modal fade" id="extraInfo" tabindex="-1" aria-labelledby="extraInfoLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="extraInfoLabel">Extra Information for <span id="item_label"></span></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <table>
                        <tr>
                            <td class="text-end">My Stock Number:</td>
                            <td class="ps-2"><span id="my_stock_number"></span></td>
                        </tr>

                        <tr>
                            <td class="text-end">Vendor Product Number:</td>
                            <td class="ps-2"><span id="vendor_product_number"></span></td>
                        </tr>

                        <tr>
                            <td class="text-end">Notes:</td>
                            <td class="ps-2"><span id="notes"></span></td>
                        </tr>
                    </table>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reports/orders.html
{% extends "orders/_list.html" %}

{% block header %}Order Report{% endblock %}

{% block data_table_handler %}
    let row = this;

    $.get(
        "{% url "orders:fetch_inventory" %}",
        {"order_id": $(row).data("id")},
        function(response) {
            let data = JSON.parse(response);
            console.log('Data = [' + $(row).data("picked_up") + ']');

            $("#item_label").html(dataTable.row(row).data()[2]);
            $("#net_cost").html($(row).data("net_cost"));
            $("#notes").html($(row).data("notes"));
            $("#payment_method").html($(row).data("payment_method"));
            $("#reference_number").html($(row).data("reference_number"));
            $("#shipping_cost").html($(row).data("shipping_cost"));
            $("#tax").html($(row).data("tax"));

            if ($(row).data("picked_up") === "None") {
                $("#picked_up").html("unknown if picked up");
            } else if ($(row).data("picked_up") === "True") {
                $("#picked_up").html("picked up");
            } else {
                $("#picked_up").html("was not picked up");
            }

            let inventory_rows = "";
            $.each(data, function(index, value) {
                inventory_rows += `<tr><td>${value[0]}</td><td>${value[1]}</td></tr>`;
            });

            $("#inventory_list").find("tr:gt(0)").remove();
            $("#inventory_list tr:last").after(inventory_rows);

            new bootstrap.Modal(document.getElementById("extraInfo")).show();
        }
    ).fail(function(jqXHR, textStatus, errorThrown) {
        alert(
            "Could not retrieve inventory information for this order.\n\nError: " + jqXHR.responseText
        );
    });
{% endblock %}

{% block instructions %}
    <p>Click on an item's row to pop up more information.</p>
{% endblock %}

{% block extra_content %}
    <div class="modal fade" id="extraInfo" tabindex="-1" aria-labelledby="extraInfoLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="extraInfoLabel">
                        Extra Information for order from <span id="item_label"></span>
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <table>
                        <tr>
                            <td class="text-end" style="width: 20%;">Reference Number:</td>
                            <td class="ps-2"><span id="reference_number"></span></td>
                        </tr>

                        <tr>
                            <td class="text-end">Net Cost:</td>
                            <td class="ps-2">$<span id="net_cost"></span></td>
                        </tr>

                        <tr>
                            <td class="text-end">Shipping Cost:</td>
                            <td class="ps-2">
                                $<span id="shipping_cost"></span>
                                (<span id="picked_up"></span>)
                            </td>
                        </tr>

                        <tr>
                            <td class="text-end">Tax:</td>
                            <td class="ps-2">$<span id="tax"></span></td>
                        </tr>

                        <tr>
                            <td class="text-end">Payment Method:</td>
                            <td class="ps-2"><span id="payment_method"></span></td>
                        </tr>

                        <tr class="top_align">
                            <td class="text-end">Notes:</td>
                            <td class="ps-2"><span id="notes"></span></td>
                        </tr>
                    </table>

                    <table class="caption-top mt-4 table table-bordered table-sm table-striped" id="inventory_list">
                        <caption style="text-align: center;"><strong>Inventory</strong></caption>

                        <tr>
                            <th>Item</th>
                            <th>Quantity</th>
                        </tr>
                    </table>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}