apps/data_transfer/urls.py
from django.conf.urls import url

from data_transfer.import_data.inventory import ImportView as ImportInventoryView
from data_transfer.import_data.orders import ImportView as ImportOrderView

app_name = 'data_transfer'
urlpatterns = [
    url(r'^import/inventory/$', ImportInventoryView.as_view(), name='import_inventory'),
    url(r'^import/orders/$', ImportOrderView.as_view(), name='import_orders')
]

apps/inventory/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import AddItemForm, UpdateItemForm
from .models import Inventory
from .views import (
    AddInventoryView, QuickQuantityUpdateView, ReportView, SaveQuantityValue, UpdateInventoryListView,
    UpdateInventoryView
)

app_name = 'inventory'
urlpatterns = [
    url(
        r'^add/$',
        AddInventoryView.as_view(
            action='Add',
            form_class=AddItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been added',
            success_url=reverse_lazy('inventory:add'),
            template_name='inventory/form.html'
        ),
        name='add'
    ),

    url(
        r'^quick/$',
        QuickQuantityUpdateView.as_view(
            model=Inventory,
            template_name='inventory/quick_quantity_update_list.html'
        ),
        name='quick_quantity_update'
    ),

    url(
        r'^report/$',
        ReportView.as_view(
            model=Inventory,
            template_name='reports/inventory.html'
        ),
        name='report'
    ),

    url(
        r'^save/quantity/$',
        SaveQuantityValue.as_view(),
        name='save_quantity_values'
    ),

    url(
        r'^update/$',
        UpdateInventoryListView.as_view(
            model=Inventory,
            template_name='inventory/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateInventoryView.as_view(
            action='Update',
            form_class=UpdateItemForm,
            model=Inventory,
            success_message='Item "%(label)s" has been updated',
            success_url=reverse_lazy('inventory:list'),
            template_name='inventory/form.html'
        ),
        name='update'
    )
]

apps/orders/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import CreateOrderForm, UpdateOrderForm
from .models import Order
from .views import CreateOrderView, FetchInventory, ReportView, UpdateOrderListView, UpdateOrderView

app_name = 'orders'
urlpatterns = [
    url(
        r'^create/$',
        CreateOrderView.as_view(
            action='Create',
            form_class=CreateOrderForm,
            model=Order,
            success_message='Order has been created',
            success_url=reverse_lazy('orders:create'),
            template_name='orders/form.html'
        ),
        name='create'
    ),

    url(
        r'^fetch/inventory/$',
        FetchInventory.as_view(),
        name='fetch_inventory'
    ),
    url(
        r'^report/$',
        ReportView.as_view(
            model=Order,
            template_name='reports/orders.html'
        ),
        name='report'
    ),

    url(
        r'^update/$',
        UpdateOrderListView.as_view(
            model=Order,
            template_name='orders/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateOrderView.as_view(
            action='Update',
            form_class=UpdateOrderForm,
            model=Order,
            success_message='Order has been updated',
            success_url=reverse_lazy('orders:list'),
            template_name='orders/form.html'
        ),
        name='update'
    )
]

shopowner/urls.py
from dashing.utils import router

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from dashboard.widgets import QuickSummaryWidget
from dashboard.wrapper import Wrapper

from library.forms import popup

router.register(QuickSummaryWidget, 'quick_summary_widget')


urlpatterns = [
    url(r'^$', Wrapper.as_view()),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^add_popup/(?P<app_label>\w*)/(?P<model_name>\w*)/', popup.popup_form),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(router.urls), name='dashboard'),
    url(r'^data_transfer/', include('data_transfer.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^orders/', include('orders.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files(?P<path>.*)$', serve, kwargs={'document_root': settings.MEDIA_ROOT})
    ]

templates/_bootstrap_form.html
{% load i18n widget_tweaks %}

<form class="form-horizontal" method="post" role="form">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    {% endif %}

    {% for field in form %}
        {% if field.errors %}
            <div class="form-group has-error">
                <div class="error-block">
                    {% for error in  field.errors %}
                        <span class="bi-arrow-down-circle">&nbsp;{{ error }}</span>
                    {% endfor %}
                </div>

                <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>

                <div class="col-sm-10">
                    {{ field|attr:"class:form-control"|attr:"style: display: inline !important; width: 98% !important;" }}
                </div>
            </div>
        {% elif field.label != "Deleted" %}
            {% comment %}
                Update form has the deleted field, add form doesn't so we are good ignoring 'Deleted' for all forms
            {% endcomment %}

            <div class="form-group">
                {% with widget_type=field|widget_type %}
                    <label class="col-sm-2 control-label" for="id_{{ field.name }}">
                        {{ field.label }}
                    </label>

                    {% if widget_type == "inlineformset" and field.help_text %}
                        <p class="help-block"><small>({{ field.help_text }})</small></p>
                    {% endif %}

                    <div class="col-sm-10">
                        {% with field_type=field|field_type %}
                            {% ifequal field_type "decimalfield" %}${% endifequal %}
                        {% endwith %}

                        {{ field|attr:"class:form-control"|attr:"style: display: inline !important; width: 98% !important;" }}

                        {% ifnotequal widget_type "inlineformset" %}
                            <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endifnotequal %}
                    </div>
                {% endwith %}
            </div>
        {% endif %}
    {% endfor %}

    {% comment %}
        If a form doesn't have the 'deleted' field, this <div></div> won't show up so it's ok to try to show it
        for all forms
    {% endcomment %}
    <div class="form-group">
        {{ form.deleted|attr:"class:form-check-input" }} {{ form.deleted.help_text }}
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10 mt-4">
            <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
        </div>
    </div>
</form>

templates/_footer.html
<footer class="mt-1">
    <p class="font-monospace" style="font-size: 0.7em !important;">
        {% if settings.DEBUG %}[Development] {% endif %}ShopOwner Applications v{{ settings.VERSION }}
        &copy; <a href="mailto:adam@csh.rit.edu">Adam Stein</a>.  All rights reserved.
    </p>
</footer>

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags for Bootstrap-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Show Owner Applications</title>

        {% block css %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

            <style>
                {% comment %}.errorlist should match Bootstrap's bg-danger CSS{% endcomment %}
                .errorlist {
                    background-color: rgba(var(--bs-danger-rgb), var(--bs-bg-opacity)) !important;
                    --bs-bg-opacity: 1;
                }

                .min-vh-with-footer {
                    min-height: 97vh !important;
                }
            </style>
        {% endblock %}

        {% block js %}
            <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.4.min.js" crossorigin="anonymous"></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        {% endblock %}
    </head>

    <body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="container-fluid p-0">
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                            {{ message }}

                            <button type="button" class="close float-end" data-bs-dismiss="alert" aria-label="Close">
                                <span aria-hidden="True">&times;</span>
                            </button>
                        </div>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-with-footer">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Menu</span>
                        </a>

                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                            <li>
                                <a href="{% url "dashboard:home" %}" class="nav-link px-0 align-middle">
                                    <em class="fs-4 bi-speedometer2"></em> <span class="ms-1 d-none d-sm-inline">
                                    Dashboard</span>
                                </a>
                            </li>

                            <li>
                                <a href="#dataTransferSubmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                    <em class="fs-4 bi-database-gear"></em>
                                    <span class="ms-1 d-none d-sm-inline">Data Transfer</span>
                                </a>

                                <ul class="collapse nav flex-column ms-1" id="dataTransferSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "data_transfer:import_inventory" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-upload"></em>
                                            <span class="d-none d-sm-inline">Import Inventory</span>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="collapse nav flex-column ms-1" id="dataTransferSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "data_transfer:import_orders" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-upload"></em>
                                            <span class="d-none d-sm-inline">Import Orders</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#inventorySubmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                    <em class="fs-4 bi-collection"></em>
                                    <span class="ms-1 d-none d-sm-inline">Inventory</span>
                                </a>

                                <ul class="collapse nav flex-column ms-1" id="inventorySubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "inventory:add" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-file-earmark"></em>
                                            <span class="d-none d-sm-inline">Add Item</span>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="collapse nav flex-column ms-1" id="inventorySubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "inventory:list" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-file-earmark-diff"></em>
                                            <span class="d-none d-sm-inline">Update Item</span>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="collapse nav flex-column ms-1" id="inventorySubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "inventory:quick_quantity_update" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-file-earmark-plus"></em>
                                            <span class="d-none d-sm-inline">Update Quantities</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#ordersSubmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                    <em class="fs-4 bi-collection"></em>
                                    <span class="ms-1 d-none d-sm-inline">Orders</span>
                                </a>

                                <ul class="collapse nav flex-column ms-1" id="ordersSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "orders:create" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-file-earmark"></em>
                                            <span class="d-none d-sm-inline">Create Order</span>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="collapse nav flex-column ms-1" id="ordersSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "orders:list" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-file-earmark-diff"></em>
                                            <span class="d-none d-sm-inline">Update Order</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#reportSubmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                    <em class="fs-4 bi-folder"></em>
                                    <span class="ms-1 d-none d-sm-inline">Reports</span>
                                </a>

                                <ul class="collapse nav flex-column ms-1" id="reportSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "inventory:report" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-collection"></em>
                                            <span class="d-none d-sm-inline">Inventory</span>
                                        </a>
                                    </li>
                                </ul>

                                <ul class="collapse nav flex-column ms-1" id="reportSubmenu" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url "orders:report" %}" class="nav-link  ps-lg-3 px-0">
                                            <em class="fs-4 bi-collection"></em>
                                            <span class="d-none d-sm-inline">Orders</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <div class="dropdown pb-4">
                            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                {% comment %}
                                In case we would want the person's picture instead of a generic icon

                                <img src="https://github.com/mdo.png" alt="{{ request.user }}" width="30" height="30" class="rounded-circle">
                                {% endcomment %}
                                <em class="fs-4 bi-person-circle"></em>
                                <span class="d-none d-sm-inline mx-1">{{ request.user }}</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                                {% comment %}
                                Might decide to use these some day

                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                {% endcomment %}

                                {% if request.user.is_superuser %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">
                                            Django Admin
                                        </a>
                                    </li>
                                {% endif %}

                                <li><a class="dropdown-item" href="{% url "logout" %}">Sign Out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col py-3">{% block content %}{% endblock %}</div>
            </div>
        </div>

        {% include "_footer.html" %}
    </body>
</html>