apps/orders/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from .forms import CreateOrderForm, UpdateOrderForm
from .models import Order
from .views import CreateOrderView, FetchInventory, ReportView, UpdateOrderListView, UpdateOrderView

app_name = 'orders'
urlpatterns = [
    url(
        r'^create/$',
        CreateOrderView.as_view(
            action='Create',
            form_class=CreateOrderForm,
            model=Order,
            success_message='Order has been created',
            success_url=reverse_lazy('orders:create'),
            template_name='orders/form.html'
        ),
        name='create'
    ),

    url(
        r'^fetch/inventory/$',
        FetchInventory.as_view(),
        name='fetch_inventory'
    ),
    url(
        r'^report/$',
        ReportView.as_view(
            model=Order,
            template_name='reports/orders.html'
        ),
        name='report'
    ),

    url(
        r'^update/$',
        UpdateOrderListView.as_view(
            model=Order,
            template_name='orders/update_list.html'
        ),
        name='list'
    ),

    url(
        r'^update/(?P<pk>[\d]+)$',
        UpdateOrderView.as_view(
            action='Update',
            form_class=UpdateOrderForm,
            model=Order,
            success_message='Order has been updated',
            success_url=reverse_lazy('orders:list'),
            template_name='orders/form.html'
        ),
        name='update'
    )
]

shopowner/urls.py
from dashing.utils import router

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from dashboard.widgets import QuickSummaryWidget
from dashboard.wrapper import Wrapper

from library.forms import popup

router.register(QuickSummaryWidget, 'quick_summary_widget')


urlpatterns = [
    url(r'^$', Wrapper.as_view()),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^add_popup/(?P<app_label>\w*)/(?P<model_name>\w*)/', popup.popup_form),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(router.urls), name='dashboard'),
    url(r'^data_transfer/', include('data_transfer.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^orders/', include('orders.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^files(?P<path>.*)$', serve, kwargs={'document_root': settings.MEDIA_ROOT})
    ]

apps/orders/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

from artifacts.models import Artifact
from inventory.models import Inventory

from vendors.models import Vendor


class Item(models.Model):
    item = models.ForeignKey(Inventory)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])

    class Meta:
        ordering = ('order', 'item')
        unique_together = ('order', 'item')

    def __str__(self):
        return f'{self.item} <--> {self.order}'


class Order(models.Model):
    deleted = models.BooleanField(default=False, help_text='Delete this order from the database')

    user = models.ForeignKey(
        User,
        help_text="User account this order belongs to"
    )

    reference_number = models.CharField(
        blank=True,
        help_text='Order number/reference number',
        max_length=20,
        null=True
    )

    vendor = models.ForeignKey(
        Vendor,
        help_text='Vendor this order was purchased from'
    )

    items = models.ManyToManyField(
        Inventory,
        help_text='Items bought in this order',
        through=Item
    )

    date_ordered = models.DateField(
        blank=True,
        help_text='Date when order was placed',
        null=True
    )

    date_received = models.DateField(
        blank=True,
        help_text='Date when order was received',
        null=True
    )

    net_cost = models.DecimalField(
        decimal_places=2,
        help_text='Net cost for the order',
        max_digits=10,
    )

    shipping_cost = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Tax credit paid for the order',
        max_digits=10,
    )

    picked_up = models.NullBooleanField(
        default=None,
        help_text='True if the order was picked up, False if shipping cost, otherwise None for unknown status'
    )

    tax = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='Tax credit paid for the order',
        max_digits=10,
    )

    payment_method = models.ForeignKey(
        'PaymentMethod',
        blank=True,
        help_text='Method of payment for this order',
        null=True
    )

    receipts = models.ManyToManyField(
        Artifact,
        blank=True,
        help_text='Uploaded receipt documents associated with this order'
    )

    notes = models.TextField(
        blank=True,
        help_text='Any miscellaneous information can go here'
    )

    class Meta:
        ordering = ('date_ordered', 'date_received', 'vendor', 'reference_number')

    @property
    def total_cost(self):
        return self.net_cost + self.shipping_cost

    def __str__(self):
        return f'[{self.vendor.name}] {self.reference_number}'


class PaymentMethod(models.Model):
    label = models.CharField(
        help_text='Method of payment',
        max_length=30,
        unique=True
    )

    class Meta:
        ordering = ('label', )

    def __str__(self):
        return self.label

apps/orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from library.forms import FormsetField, HTML5DateInput, SelectWithAdd, SelectMultipleWithAdd

from .models import Item, Order

from inventory.models import Inventory


class ItemForm(forms.ModelForm):
    class Meta:
        exclude = ()
        model = Item
        widgets = {
            'item': SelectWithAdd(Item.item)
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['item'].queryset = Inventory.objects.filter(user=user)


ItemFormSet = forms.inlineformset_factory(Order, Item, exclude=['order'], extra=0, form=ItemForm)


class BaseOrderForm(forms.ModelForm):
    items = FormsetField(
        error_messages={
            'invalid': 'Quantity must be greater than 0',
            'required': 'Items bought in this order must be listed'
        },
        formset=ItemFormSet,
        help_text='Items bought in this order'
    )

    class Meta:
        fields = [
            'date_ordered', 'date_received', 'vendor', 'reference_number', 'items', 'net_cost', 'shipping_cost', 'tax',
            'payment_method', 'receipts', 'notes'
        ]
        model = Order
        widgets = {
            'date_ordered': HTML5DateInput(),
            'date_received': HTML5DateInput(),
            'payment_method': SelectWithAdd(Order.payment_method),
            'receipts': SelectMultipleWithAdd(
                Order.receipts, parameters={'category': 'receipt', 'directory': 'receipts'}
            ),
            'vendor': SelectWithAdd(Order.vendor)
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['items'].create_widget(ItemFormSet, form_kwargs={'instance': kwargs['instance'], 'user': user})


class CreateOrderForm(BaseOrderForm):
    update_quantity = forms.BooleanField(widget=forms.HiddenInput(), required=False)


class UpdateOrderForm(BaseOrderForm):
    class Meta(BaseOrderForm.Meta):
        fields = [
            'date_ordered', 'date_received', 'reference_number', 'vendor', 'items', 'net_cost', 'shipping_cost',
            'tax', 'payment_method', 'receipts', 'notes', 'deleted'
        ]

    def clean(self):
        cleaned_data = super().clean()

        if len(cleaned_data['items'].deleted_forms) == len(cleaned_data['items']):
            raise ValidationError('Items bought in this order must be listed', code='required')

        return cleaned_data

apps/orders/views.py
from django.http import HttpResponseRedirect

from .models import Order

from library.views.generic import AppCreateView, AppListView, AppTemplateView, AppUpdateView
from library.views.generic.mixins.ajax import AJAXResponseMixin


class CreateOrderView(AppCreateView):
    object = None

    def form_valid(self, form):
        update_quantity = 'update_quantity' in form.cleaned_data and form.cleaned_data['update_quantity']

        self.object = form.save(commit=False)
        if self.object.shipping_cost:
            self.object.picked_up = False
        self.object.user = self.request.user
        self.object.save()

        for item in form.cleaned_data['items'].save(commit=False):
            item.order = self.object
            item.save()

            if update_quantity:
                item.item.qty_bought += item.quantity
                item.item.save()

        if self.success_message:
            self.success_message = self.success_message % form.cleaned_data

        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class FetchInventory(AJAXResponseMixin, AppTemplateView):
    def get_context_data(self, **kwargs):
        order = Order.objects.get(id=self.request.GET['order_id'])
        ret = []
        for item in order.item_set.all():
            ret.append([item.item.label, item.quantity])
        return ret


class ReportView(AppListView):
    pass


class UpdateOrderListView(AppListView):
    pass


class UpdateOrderView(AppUpdateView):
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.shipping_cost:
            self.object.picked_up = False
        self.object.user = self.request.user
        self.object.save()

        for item in form.cleaned_data['items'].deleted_forms:
            item.instance.delete()

        for item in form.cleaned_data['items'].save(commit=False):
            item.order = self.object
            item.save()

        if self.success_message:
            self.success_message = self.success_message % form.cleaned_data

        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

templates/orders/_list.html
{% extends "reports/_list_base.html" %}


{% block data_table_headers %}
    <th>Date Ordered</th>
    <th>Date Received</th>
    <th>Vendor</th>
    <th>Total Cost</th>
    <th>Receipts</th>
{% endblock %}

{% block data_table_data %}
    {% for order in object_list %}
        <tr data-id="{{ order.id }}" data-reference_number="{{ order.reference_number|default_if_none:"" }}"
            data-net_cost="{{ order.net_cost }}" data-notes="{{ order.notes|linebreaksbr }}"
            data-payment_method="{{ order.payment_method|default_if_none:"" }}"
            data-picked_up="{{ order.picked_up }}"
            data-shipping_cost="{{ order.shipping_cost }}" data-tax="{{ order.tax }}">
            <td>{{ order.date_ordered|default_if_none:"" }}</td>
            <td>{{ order.date_received|default_if_none:"" }}</td>
            <td>
                {% if order.vendor.website %}
                    <a href="{{ order.vendor.website }}" target="_blank">{{ order.vendor }}</a>
                {% else %}
                    {{ order.vendor }}
                {% endif %}
            </td>
            <td class="text-end">${{ order.total_cost }}</td>
            <td>
                <ol>
                    {% for receipt in order.receipts.all %}
                        <li>
                            <a href="{{ receipt.file.url }}" target="_blank">
                                {{ receipt.original_filename }}
                            </a>
                        </li>
                    {% endfor %}
                </ol>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block data_table_no_item_label %}orders{% endblock %}

templates/orders/form.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}

    <link rel="stylesheet" type="text/css" href="{% static "css/inline.css" %}" />
{% endblock %}

{% block js %}
    {{ block.super }}

    <script src="{% static "admin/js/jquery.init.js" %}" type="text/javascript"></script>
    <script src="{% static "admin/js/admin/RelatedObjectLookups.js" %}" type="text/javascript"></script>

    <script>
        $ = django.jQuery;

        $(document).ready(function () {
            {% ifequal action "Create" %}
                $("form").submit(function() {
                    if ($("#id_update_quantity").val()) {
                        return true;
                    } else {
                        // Allow the user to decide to update the inventory count with the info from this new order
                        new bootstrap.Modal(document.getElementById('inventoryUpdateModal')).show();
                        return false;
                    }
                });
            {% endifequal %}

            $(".modal-button").click(function() {
                $("#id_update_quantity").val(($(this).text() === "Yes") ? "True" : "False")
                $("form").submit();
            });
        });
    </script>
{% endblock %}


{% block content %}
    <div class="pb-2 mt-4 mb-2 border-bottom"><h1>{{ action }} Order</h1></div>

    {% include "_bootstrap_form.html" %}

    <div class="modal fade" id="inventoryUpdateModal" data-bs-backdrop="static" tabindex="-1" data-bs-keyboard="false"
         aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle">Update Inventory Quantity</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    Should the inventory <em>Quantity Bought</em> amount be updated given the information in this
                    new order?
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary modal-button" data-bs-dismiss="modal">Yes</button>
                    <button type="button" class="btn btn-secondary modal-button" data-bs-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/orders/update_list.html
{% extends "orders/_list.html" %}

{% block header %}Update Order{% endblock %}

{% block data_table_handler %}
    window.location.replace("{% url "orders:update" 0 %}".replace('0', $(this).data("id")));
{% endblock %}

{% block instructions %}
    <p>Click on an order's row to edit the information.</p>
{% endblock %}